# Generated by Django 3.1.3 on 2020-12-22 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='modified_time',
        ),
    ]
