# Generated by Django 3.1.3 on 2020-12-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201222_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='created_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='modified_time',
            field=models.DateTimeField(null=True),
        ),
    ]
