# Generated by Django 3.1.3 on 2020-12-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201225_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='city',
            field=models.CharField(default='NA', max_length=30),
        ),
        migrations.AddField(
            model_name='broker',
            name='firstname',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AddField(
            model_name='broker',
            name='lastname',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AddField(
            model_name='broker',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='NA', max_length=30),
        ),
        migrations.AddField(
            model_name='customer',
            name='firstname',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='lastname',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
