# Generated by Django 3.1.3 on 2020-12-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201226_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='city',
            field=models.CharField(blank=True, default='NA', max_length=30),
        ),
        migrations.AlterField(
            model_name='broker',
            name='firstname',
            field=models.CharField(blank=True, default='NA', max_length=10),
        ),
        migrations.AlterField(
            model_name='broker',
            name='lastname',
            field=models.CharField(blank=True, default='NA', max_length=10),
        ),
    ]
