# Generated by Django 3.1.3 on 2020-12-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20201226_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='department_name',
            field=models.CharField(default='NA', max_length=30),
        ),
        migrations.AlterField(
            model_name='broker',
            name='location',
            field=models.CharField(default='india', max_length=30),
        ),
    ]
