# Generated by Django 3.1.3 on 2020-12-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20201226_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
