# Generated by Django 3.1.3 on 2020-12-30 07:19

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20201230_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='work',
            field=multiselectfield.db.fields.MultiSelectField(max_length=200),
        ),
    ]
