# Generated by Django 3.1.3 on 2020-12-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20201230_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='profile_pic',
            field=models.ImageField(default='profile_pic/nan1.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(default='profile_pic/nan1.jpg', upload_to='profile_pics'),
        ),
    ]
