# Generated by Django 3.1.3 on 2020-12-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20201230_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='profile_pic',
            field=models.ImageField(default='profile_pic/nan1.jpg', upload_to='profile_pics'),
        ),
    ]
