# Generated by Django 3.1.3 on 2020-12-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_broker_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(default='profile_pic/nan1.jpg', upload_to='profile_pics'),
        ),
    ]
