# Generated by Django 3.1.3 on 2020-12-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20201231_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='avg_rating',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='rated_cust',
        ),
        migrations.AddField(
            model_name='broker',
            name='avg_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='broker',
            name='rated_cust',
            field=models.IntegerField(default=0),
        ),
    ]
