# Generated by Django 3.1.3 on 2021-01-01 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20210101_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='broker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='present_b', to='accounts.broker'),
        ),
        migrations.AddField(
            model_name='chat',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='present_c', to='accounts.customer'),
        ),
    ]
