# Generated by Django 3.1.3 on 2021-01-01 13:45

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_remove_chat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='name',
            field=multiselectfield.db.fields.MultiSelectField(default=None, max_length=200),
        ),
    ]
